apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: nginx
        image: nginx-demo-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      - name: spring
        image: demo:1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

