apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
  - name: nginx
    image: nginx-demo-proxy:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
  - name: spring
    image: demo:0.0.1-SNAPSHOT
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

